### PR TITLE
Add eval_reward to TensorBoardLogger

### PR DESCRIPTION
**Pull request by PeggyYuchunWang**
Double check if this is actually the eval_reward?

### CODE REVIEW

**Comment by MaximeBouton** [comment]
I think you might want to place it over here instead: https://github.com/JuliaPOMDP/DeepQLearning.jl/blob/11cbf72c961f1d2782e4bc27173feb8bb7fd53a7/src/solver.jl#L131

So that we don't log it more than once.

**Comment by PeggyYuchunWang** [comment]
Done! Would that work?

**Comment by MaximeBouton** [comment]
yes, did you visualize the log? does it look good?

**Comment by PeggyYuchunWang** [comment]
Not yet for eval reward bc I'm assuming I have to do it in dev mode - I can try now. But the rest of the logs look good

**Comment by PeggyYuchunWang** [comment]
Also - not sure if logging for average reward in the terminal is correct - will make a issue

```
16500 / 1000000 eps 0.967 |  avgR -0.997 | Loss 4.184e-03 | Grad 9.393e-03 
17000 / 1000000 eps 0.966 |  avgR -0.997 | Loss 5.712e-03 | Grad 1.264e-02 
```

**Pull request merged**
