### PR TITLE
Fix Bug in Solver

### PR DESCRIPTION
**Pull request by PeggyYuchunWang**
Fixed bug where if save frequency and evaluation frequency was different, it would save the wrong model.

### CODE REVIEW

**Comment by MaximeBouton** [comment]
Thanks Peggy!
The tests are failing though, can you check locally if they pass?

**Comment by PeggyYuchunWang** [comment]
```
vanilla DQN: Test Failed at /home/travis/build/JuliaPOMDP/DeepQLearning.jl/test/runtests.jl:33
  Expression: r_basic >= 1.5
   Evaluated: 1.0870397009999981 >= 1.5
Stacktrace:
 [1] macro expansion at /home/travis/build/JuliaPOMDP/DeepQLearning.jl/test/runtests.jl:33 [inlined]
 [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
 [3] top-level scope at /home/travis/build/JuliaPOMDP/DeepQLearning.jl/test/runtests.jl:24
Test Summary: | Fail  Total
vanilla DQN   |    1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /home/travis/build/JuliaPOMDP/DeepQLearning.jl/test/runtests.jl:23
ERROR: Package DeepQLearning errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:120
 [2] #test#65(::Bool, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1357
 [3] #test at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:0 [inlined]
 [4] #test#42(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:273
 [5] #test at ./none:0 [inlined]
 [6] #test#41 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:255 [inlined]
 [7] #test at ./none:0 [inlined]
 [8] #test#40 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:254 [inlined]
 [9] #test at ./none:0 [inlined]
 [10] #test#39 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:253 [inlined]
 [11] (::getfield(Pkg.API, Symbol("#kw##test")))(::NamedTuple{(:coverage,),Tuple{Bool}}, ::typeof(Pkg.API.test), ::String) at ./none:0
 [12] top-level scope at none:0
The command "julia --project --color=yes --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("DeepQLearning"; coverage=true)'" exited with 1.
```

**Comment by PeggyYuchunWang** [comment]
```
vanilla DQN: Test Failed at /home/travis/build/JuliaPOMDP/DeepQLearning.jl/test/runtests.jl:33
  Expression: r_basic >= 1.5
   Evaluated: 1.0870397009999981 >= 1.5
Stacktrace:
 [1] top-level scope at /home/travis/build/JuliaPOMDP/DeepQLearning.jl/test/runtests.jl:33
 [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
 [3] top-level scope at /home/travis/build/JuliaPOMDP/DeepQLearning.jl/test/runtests.jl:24
Test Summary: | Fail  Total
vanilla DQN   |    1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /home/travis/build/JuliaPOMDP/DeepQLearning.jl/test/runtests.jl:23
ERROR: Package DeepQLearning errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:120
 [2] #test#66(::Bool, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1328
 [3] #test at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:0 [inlined]
 [4] #test#44(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:193
 [5] #test at ./none:0 [inlined]
 [6] #test#43 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:175 [inlined]
 [7] #test at ./none:0 [inlined]
 [8] #test#42 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:174 [inlined]
 [9] #test at ./none:0 [inlined]
 [10] #test#41(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:coverage,),Tuple{Bool}}}, ::Function, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:173
 [11] (::getfield(Pkg.API, Symbol("#kw##test")))(::NamedTuple{(:coverage,),Tuple{Bool}}, ::typeof(Pkg.API.test), ::String) at ./none:0
 [12] top-level scope at none:0
The command "julia --project --color=yes --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("DeepQLearning"; coverage=true)'" exited with 1.
Done. Your build exited with 1.
```

**Comment by PeggyYuchunWang** [comment]
@MaximeBouton how do I run the test locally?

**Comment by PeggyYuchunWang** [comment]
Same error locally:
```
vanilla DQN: Test Failed at /Users/pegasus/.julia/dev/DeepQLearning/test/runtests.jl:33
  Expression: r_basic >= 1.5
   Evaluated: 1.0870397009999981 >= 1.5
Stacktrace:
 [1] top-level scope at /Users/pegasus/.julia/dev/DeepQLearning/test/runtests.jl:33
 [2] top-level scope at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
 [3] top-level scope at /Users/pegasus/.julia/dev/DeepQLearning/test/runtests.jl:24
Test Summary: | Fail  Total
vanilla DQN   |    1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /Users/pegasus/.julia/dev/DeepQLearning/test/runtests.jl:23
```

**Comment by MaximeBouton** [comment]
it might just be the random seed, can you try to change it?

**Comment by PeggyYuchunWang** [comment]
@MaximeBouton fixed (changed seed to 7), ready to merge?

**Comment by MaximeBouton** [comment]
yes, if you have any idea to make these tests more robust let me know :)

**Pull request merged**
