### PR TITLE
Support AbstractArray in DQExperience

### PR DESCRIPTION
**Pull request by MaximeBouton**
This should work with the change in JuliaPOMDP/RLInterface.jl#31

#31

### CODE REVIEW

**Comment by MaximeBouton** [comment]
@zsunberg do you have a minimum example for #31 that I could add to the test suite?

**Comment by zsunberg** [comment]
Sure! I'll add one!

**Comment by zsunberg** [comment]
This is what I would expect to work: (sorry I don't have time to get it to work right now)

```
mutable struct StaticArrayEnv <: AbstractEnvironment{typeof(SVector(1))}
    state::typeof(SVector(1))
end

RLInterface.actions(::StaticArrayEnv) = [0,1]

function RLInterface.reset!(env::StaticArrayEnv)
    env.state = SVector(1)
end

function RLInterface.step!(env::StaticArrayEnv, a)
    env.state += SVector(a)
    return env.state, env.state[1]^2, env.state[1] >= 2, NamedTuple()
end

env = StaticArrayEnv()

model = Chain(Dense(1, 32), Dense(32, length(actions(env))))


solver = DeepQLearningSolver(qnetwork = model, max_steps=10, 
                             learning_rate=0.005,log_freq=500,
                             recurrence=false,double_q=true, dueling=true, prioritized_replay=true)
policy = solve(solver, env)
```

**Comment by MaximeBouton** [comment]
I changed your example a bit, I used an MDP instead of `AbtractEnvironment`. 
It is using the env.problem field at several places. I think it would need another PR to fix this.

**Pull request merged**
